[functions.send-session-notification]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-corporate-user]
verify_jwt = false

[functions.link-corporate]
verify_jwt = false

[functions.course-ai-generate]
verify_jwt = false

[functions.manage-corporates]
verify_jwt = false

[functions.course-create-order]
verify_jwt = false

[functions.course-verify-payment]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false
